import Head from "next/head"
import { useContext } from "react"
import { DndProvider } from "react-dnd"
import { HTML5Backend } from "react-dnd-html5-backend"

import GlobalStyles from "../styles/GlobalStyles"
import { StyledIndex } from "../styles/index.styles"

import { MyContext } from "../components/Context"
import Contacts from "../components/Contacts/Contacts"
import Groups from "../components/Groups/Groups"
import GroupForm from "../components/Groups/Form"
import ContactForm from "../components/Contacts/Form"

export default function Home() {
    const { modal } = useContext(MyContext)

    return (
        <StyledIndex>
            <GlobalStyles />
            <Head>
                <title>Contacts App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="title">Contacts App</div>

            {modal === "contact" && <ContactForm />}
            {modal === "group" && <GroupForm />}

            <DndProvider backend={HTML5Backend}>
                <Contacts />
                <Groups />
            </DndProvider>
        </StyledIndex>
    )
}
