import Head from "next/head"
import { useContext } from "react"
import { DndProvider } from "react-dnd"
import { HTML5Backend } from "react-dnd-html5-backend"

import { MyContext } from "../components/Context"
import Contacts from "../components/Contacts/Contacts"
import Groups from "../components/Groups/Groups"
import GroupForm from "../components/Groups/Form"
import ContactForm from "../components/Contacts/Form"
import styled from "styled-components"
import GlobalStyles from "../styles/GlobalStyles"
import Modal from "../components/Modal"

const StyledIndex = styled.div`
    display: flex;
    align-items: center;
    justify-content: center;

    width: 100vw;
    height: 100vh;
    padding: 2rem;
    gap: 1rem;
`

export default function Home() {
    const { modal } = useContext(MyContext)

    return (
        <StyledIndex>
            <GlobalStyles />
            <Head>
                <title>Contacts App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {modal && (
                <Modal>
                    {modal === "contact" && <ContactForm />}
                    {modal === "group" && <GroupForm />}
                </Modal>
            )}

            <DndProvider backend={HTML5Backend}>
                <Contacts />
                <Groups />
            </DndProvider>
        </StyledIndex>
    )
}
