import Head from "next/head"

import GlobalStyles from "../styles/GlobalStyles"
import { StyledIndex } from "../styles/index.styles"

import { useContext, useEffect } from "react"
import { MyContext } from "../components/Context"
import { DragDropContext, resetServerContext } from "react-beautiful-dnd"
import Contacts from "../components/Contacts/Contacts"
import Groups from "../components/Groups/Groups"
import GroupForm from "../components/Groups/Form"
import ContactForm from "../components/Contacts/Form"

export default function Home() {
    const { modal } = useContext(MyContext)
    resetServerContext()

    return (
        <StyledIndex>
            <GlobalStyles />
            <Head>
                <title>Contacts App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="title">Contacts App</div>

            {modal === "contact" && <ContactForm />}
            {modal === "group" && <GroupForm />}

            <DragDropContext id>
                <Contacts />
                <Groups />
            </DragDropContext>
        </StyledIndex>
    )
}
